# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88cf9f5f4caef8bcadd239f1cb709f8d577d80b54e26545b52e1e3caae41b08e3271b823630ed642e3abc196bea11958aaacf04cc93c7576b6117ec366391bd2

test:
  secret_key_base: 8430d13efaca0d576ddb12fd49f85fa19171c4fc19357d04eefc817248b0c20dfb4cf0cd1df2a2cf990cafa2847a666154972f1d8fcaa126e1bc58fbc8fe6019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
